In [3]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
         [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  260.27954 
Prediction:
 [[158.21486]
 [205.8143 ]
 [194.47911]
 [214.21855]
 [158.96991]]
100 Cost:  18.574795 
Prediction:
 [[144.6139 ]
 [189.15376]
 [178.22656]
 [196.49591]
 [146.20415]]
200 Cost:  17.659695 
Prediction:
 [[144.77577]
 [189.04337]
 [178.27681]
 [196.52713]
 [146.06361]]
300 Cost:  16.792572 
Prediction:
 [[144.93333]
 [188.93585]
 [178.32576]
 [196.5574 ]
 [145.92688]]
400 Cost:  15.970935 
Prediction:
 [[145.08675]
 [188.83119]
 [178.37343]
 [196.58675]
 [145.79388]]
500 Cost:  15.192411 
Prediction:
 [[145.2361 ]
 [188.72932]
 [178.41985]
 [196.6152 ]
 [145.66449]]
600 Cost:  14.454672 
Prediction:
 [[145.38153]
 [188.63014]
 [178.46506]
 [196.6428 ]
 [145.53865]]
700 Cost:  13.755572 
Prediction:
 [[145.52313]
 [188.53358]
 [178.5091 ]
 [196.66956]
 [145.41624]]
800 Cost:  13.0931 
Prediction:
 [[145.66101]
 [188.43959]
 [178.552  ]
 [196.69551]
 [145.2972 ]]
900 Cost:  12.465314 
Prediction:
 [[145.79524]
 [188.34807]
 [178.5938 ]
 [196.72069]
 [145.18