In [6]:
import tensorflow as tf

x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict = {X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
            h, c, a = sess.run([hypothesis, predicted, accuracy],
                              feed_dict={X: x_data, Y: y_data})
            print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: ", a)

0 5.6320024

Hypothesis: 
 [[4.64299619e-02]
 [2.81703472e-03]
 [3.26475501e-03]
 [7.00056553e-05]
 [1.10255405e-05]
 [4.71084604e-06]] 
Correct (Y): 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.5
1000 0.51020914

Hypothesis: 
 [[0.29104024]
 [0.2717655 ]
 [0.7777572 ]
 [0.59373   ]
 [0.7430633 ]
 [0.9256965 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
2000 0.4228586

Hypothesis: 
 [[0.19251391]
 [0.22164929]
 [0.7280459 ]
 [0.6164944 ]
 [0.7925036 ]
 [0.94750834]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
3000 0.35846698

Hypothesis: 
 [[0.14635488]
 [0.21114546]
 [0.6578449 ]
 [0.6434539 ]
 [0.8241321 ]
 [0.95291513]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
4000 0.30838212

Hypothesis: 
 [[0.11539444]
 [0.20585519]
 [0.5884696 ]
 [0.6690712 ]
 [0.8495438 ]
 [0.9568274 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
5000 0.26912862

Hypothesis: 
 [